baseURL = "/"
languageCode = "es-cl"
DefaultContentLanguage = "es"

title = "Movilidad Sodimac | Open Api Documentation"
theme = "hugo-theme-docdock"

[params]
editURL = "https://github.com/Mobile-Studio/api-docs/edit/master/site/content/"
showVisitedLinks = false # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i>&nbsp;&nbsp;&nbsp;Github repositorie"
identifier = "ds"
url = "https://github.com/Mobile-Studio/api-docs"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i>&nbsp;&nbsp;&nbsp;Credits"
url = "/credits"
weight = 30